### ISSUE TITLE
1. Get Started with Xcode!

### ISSUE THREAD

**Issue by chuckySF** [MakeSchool-Tutorials/Getting-Started-With-Xcode-2017#1]
Looks like latest Xcode should be 8.3.3?

Original:
You should be on macOS Sierra (10.12.5) and have Xcode 8.3.2. DO NOT INSTALL ANY DEVELOPER PREVIEWS OF OS X, iOS, OR Xcode!!!

Correction:
You should be on macOS Sierra (10.12.5) and have Xcode **8.3.3**. DO NOT INSTALL ANY DEVELOPER PREVIEWS OF OS X, iOS, OR Xcode!!!

**Comment by dionlarson** [comment]
Yes, was released yesterday. Will update 👍
