### ISSUE TITLE
Progress doesn't fill in after completing the "Install Xcode" tutorial.

### ISSUE THREAD

**Issue by TheoBendixson** [MakeSchool-Tutorials/Getting-Started-With-Xcode-2017#2]
Reproduction Steps:

1. Navigate to the "Getting Started With Xcode" lesson and click "Start".
2. Mark each item as complete.
3. Click "Finished! To Dashboard."

Expected Result:
1. The label displaying "X of 1 steps completed" displays "1 of 1 steps competed"
2. The "Track Progress" bar up top shows some percentage filled.

Actual Result:
1. The label under "Getting Started with Xcode" shows "0 of 1 steps completed."
2. The "Track Progress" bar up top shows 0% completed.

**Comment by dionlarson** [comment]
Show be fixed now.
